# Generated by Django 3.2.4 on 2021-06-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('name',), 'verbose_name': 'store', 'verbose_name_plural': 'stores'},
        ),
    ]
